#! /bin/sh

# Autostart WM dependent applications
sxhkd &
dunst &
picom -b &
setbg &
unclutter &
$HOME/.config/polybar/launch.sh &

# Fix java reparenting issue
# Mainly only an issue with PhpStorm and bspwm
wmname LG3D &

# Consider setting this dynamically
bspc monitor DP-2 -d WWW GFX TRM DOC SYS
bspc monitor DP-4 -d DEV MUS CNF GME VPN

bspc config border_width        3
bspc config window_gap          10
bspc config top_padding         27

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# The only time this is annoying is when trying
# to move tabs between chrome windows.
bspc config focus_follows_pointer   true
bspc config pointer_follows_focus   true

# Solarized-ish colors
bspc config normal_border_color    "#586e75"
bspc config activer_border_color   "#002b36"
bspc config focused_border_color   "#859900"
bspc config presel_feedback_color  "#2aa198"
bspc config urgent_border_color    "#dc322f"

bspc rule -a Brave-browser desktop='^1' follow=on
bspc rule -a st-vpn desktop='^10' follow=on
bspc rule -a st-calcurse desktop='^3' follow=on
bspc rule -a st-sxhkd-help state=floating
bspc rule -a Emacs state=tiled desktop='^6' follow=on
bspc rule -a jetbrains-phpstorm desktop='^6' follow=on
bspc rule -a jetbrains-datagrip desktop='^6' follow=on
bspc rule -a st-config-dotfile desktop='^8' follow=on
bspc rule -a Spotify desktop='^7' follow=on
bspc rule -a Peek state=floating
bspc rule -a Steam desktop='^9' follow=on

